export const orderData = [
    {
      id: "1",
      customer: "Khách lẻ\nZKXSQZ-HT01",
      date: "15/11/2023 20:23",
      status: "Trả hàng",
      statusColor: "returned",
      total: "650.001",
      payment: false,
      action: "Đã giao",
    },
    {
      id: "2",
      customer: "Khách lẻ\nAASTRN",
      date: "15/11/2023 14:47",
      status: "Đang xử lý",
      statusColor: "processing",
      total: "650.001",
      payment: false,
      action: "",
    },
    {
      id: "3",
      customer: "Khách lẻ\nDMVZU",
      date: "14/11/2023 18:59",
      status: "Đã hủy",
      statusColor: "debt",
      total: "1.530.000",
      payment: false,
      action: "",
    },
    {
      id: "4",
      customer: "Khách lẻ\nMH5ZZV",
      date: "14/11/2023 11:26",
      status: "Đã hủy",
      statusColor: "debt",
      total: "85.000",
      payment: false,
      action: "",
    },
    {
      id: "5",
      customer: "Khách lẻ\nDZ6GEV",
      date: "13/11/2023 14:28",
      status: "Đã hủy",
      statusColor: "debt",
      total: "200.000",
      payment: false,
      action: "",
    },
  ];
  